---
apiVersion: v2
name: kube-prometheus-stack-subchart
type: application
version: 1.0.0
appVersion: "0.54.0"
dependencies:
  - name: kube-prometheus-stack
    version: 45.21.0
    repository: https://prometheus-community.github.io/helm-charts
