app-template:
  controllers:
    openwakeword:
      strategy: Recreate
      containers:
        maniek:
          image:
            repository: rhasspy/wyoming-openwakeword
            tag: 2.1.0@sha256:52cb1168731a1849fc28cf339c935fde58746bbabc94226668a40ef6ddf5d42b
            pullPolicy: IfNotPresent
          args:
            - --custom-model-dir
            - /custom
          resources:
            requests:
              cpu: 500m
              memory: 200Mi
            limits:
              cpu: 2000m
              memory: 1Gi
          probes:
            liveness:
              enabled: true
            readiness:
              enabled: true
            startup:
              enabled: true
      initContainers:
        load-model:
          image:
            repository: public.ecr.aws/docker/library/alpine
            tag: latest@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659
            pullPolicy: IfNotPresent
          command:
            - "/bin/sh"
            - -c
          args:
            - cd /custom && apk --no-cache add curl && curl -sLO https://raw.githubusercontent.com/mmalyska/home-ops/main/cluster/home-automation/openwakeword/hey_maniek.tflite
  service:
    maniek:
      annotations:
        io.cilium/lb-ipam-sharing-key: "voice-pipeline"
        lbipam.cilium.io/sharing-cross-namespace: "*"
      type: LoadBalancer
      loadBalancerIP: 192.168.48.27
      controller: openwakeword
      ports:
        tcp:
          port: 10400
  persistence:
    custom:
      type: emptyDir
