persistance:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
minecraft-bedrock:
  image:
    repository: itzg/minecraft-bedrock-server
    tag: 2025.12.2@sha256:70370705432e9f6fe0d75754d4b3830acbe64cf4c9afe0ec9c9cb3b598a18be1
    pullPolicy: IfNotPresent
  persistence:
    dataDir:
      enabled: true
      existingClaim: minecraft-bedrock-datadir
      Size: 10Gi
  resources:
    requests:
      memory: 250Mi
      cpu: 200m
    limits:
      memory: 1Gi
  minecraftServer:
    eula: "TRUE"
    version: 1.21.111.1
    difficulty: normal
    gameMode: survival
    levelName: jaskinia
    serverName: "Jaskinia"
    cheats: false
    serviceType: LoadBalancer
    loadBalancerIP: 192.168.48.23
    ops: <secret:ops>
    defaultPermission: visitor
    whitelistUsers: <secret:whitelistUsers>
