persistance:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
minecraft-bedrock:
  image:
    repository: itzg/minecraft-bedrock-server
    tag: 2026.2.1@sha256:f081b6f19dc576518e71764fd80c8a4504ecb0381013e8ed7043c5a5a5fb3095
    pullPolicy: IfNotPresent
  persistence:
    dataDir:
      enabled: true
      existingClaim: minecraft-bedrock-datadir
      Size: 10Gi
  resources:
    requests:
      memory: 250Mi
      cpu: 200m
    limits:
      memory: 1Gi
  minecraftServer:
    eula: "TRUE"
    version: 1.21.111.1
    difficulty: normal
    gameMode: survival
    levelName: jaskinia
    serverName: "Jaskinia"
    cheats: false
    serviceType: LoadBalancer
    loadBalancerIP: 192.168.48.23
    ops: <secret:ops>
    defaultPermission: visitor
    whitelistUsers: <secret:whitelistUsers>
