app-template:
  controllers:
    piper:
      strategy: Recreate
      containers:
        pl:
          image:
            repository: rhasspy/wyoming-piper
            tag: 2.2.2@sha256:c874e4a04657ae3381332ee5d0c8c70a310dae6722892840f530ac0890b44eb3
            pullPolicy: IfNotPresent
          args:
            - --voice
            - pl_PL-darkman-medium
            - --update-voices
          resources:
            requests:
              cpu: 1000m
              memory: 1Gi
            limits:
              cpu: 4000m
              memory: 2Gi
          probes:
            liveness:
              enabled: true
            readiness:
              enabled: true
            startup:
              enabled: true
  service:
    pl:
      annotations:
        io.cilium/lb-ipam-sharing-key: "voice-pipeline"
        lbipam.cilium.io/sharing-cross-namespace: "*"
      type: LoadBalancer
      loadBalancerIP: 192.168.48.27
      controller: piper
      ports:
        tcp:
          port: 10200
  persistence:
    data:
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 10Gi
