---
apiVersion: v2
name: external-traefik-subchart
type: application
version: 1.0.0
appVersion: "2.6.1"
dependencies:
  - name: traefik
    version: 28.1.0
    repository: https://traefik.github.io/charts
