app-template:
  controllers:
    whisper:
      strategy: Recreate
      containers:
        pl:
          image:
            repository: rhasspy/wyoming-whisper
            tag: 3.1.0@sha256:9501d2659eee83b6eead98d53842193e5fed011eda6c5b1c3ad36f3146b28fed
            pullPolicy: IfNotPresent
          args:
            - --language
            - pl
            - --model
            - base-int8
            - --data-dir
            - /data
          env:
            HF_HUB_CACHE: "/model-cache"
          resources:
            requests:
              cpu: 1000m
              memory: 1Gi
            limits:
              cpu: 4000m
              memory: 4Gi
          probes:
            liveness:
              enabled: true
            readiness:
              enabled: true
            startup:
              enabled: true
              spec:
                initialDelaySeconds: 0
                periodSeconds: 10
                timeoutSeconds: 1
                failureThreshold: 30

  service:
    pl:
      annotations:
        io.cilium/lb-ipam-sharing-key: "voice-pipeline"
        lbipam.cilium.io/sharing-cross-namespace: "*"
      type: LoadBalancer
      loadBalancerIP: 192.168.48.27
      controller: whisper
      ports:
        tcp:
          port: 10300
  persistence:
    data:
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 10Gi
    model-cache:
      type: emptyDir
