open-webui:
  ollama:
    enabled: false
  ingress:
    enabled: true
    class: "traefik"
    host: chat.<secret:private-domain>
    tls: false
  image:
    repository: ghcr.io/open-webui/open-webui
    tag: "v0.8.5@sha256:2deb90b0423473d8f97febced2e62b8fd898aa3eb61877bb3aa336370214c258"
    pullPolicy: "IfNotPresent"
  websocket:
    enabled: false
